
services:

  postgres:
    image: postgres:18
    container_name: postgres
    environment:
      POSTGRES_DB: helloapi_db
      POSTGRES_USER: helloapi_postgres
      POSTGRES_PASSWORD: helloapi_postgres_1234
    ports:
      - "5432:5432"

    # For testing purpose only, to simulate persistence
    volumes:
      - postgres_volume_data:/var/lib/postgresql

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

# For testing purpose only, to simulate persistence
volumes:
  postgres_volume_data: